SELECT YEAR(SALES_DATE) YEAR,
       MONTH(SALES_DATE) MONTH,
       COUNT(DISTINCT(OS.USER_ID)) PURCHASED_USERS,
       ROUND(COUNT(DISTINCT(OS.USER_ID)) / (SELECT COUNT(USER_ID) C
                                            FROM USER_INFO
                                            WHERE JOINED LIKE '2021-%'), 1) PUCHASED_RATIO
FROM ONLINE_SALE OS INNER JOIN USER_INFO UI
                               ON OS.USER_ID = UI.USER_ID AND JOINED LIKE '2021-%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
