WITH A_TABLE as 
(
    SELECT 'A' GRADE, ID, EMAIL
    FROM DEVELOPERS, SKILLCODES
    WHERE SKILL_CODE & CODE AND CATEGORY = 'Front End'
    AND ID IN (SELECT ID
            FROM DEVELOPERS, SKILLCODES
            WHERE SKILL_CODE & CODE AND NAME = 'Python')
), B_TABLE as
(
    SELECT 'B' GRADE, ID, EMAIL
    FROM DEVELOPERS, SKILLCODES
    WHERE SKILL_CODE & CODE AND NAME = 'C#'
        AND ID NOT IN (SELECT ID FROM A_TABLE)
)

SELECT * FROM A_TABLE
UNION 
SELECT * FROM B_TABLE
UNION
SELECT 'C' GRADE, ID, EMAIL
FROM DEVELOPERS, SKILLCODES
WHERE SKILL_CODE & CODE AND CATEGORY = 'Front End'
AND ID NOT IN (SELECT ID FROM A_TABLE)
AND ID NOT IN (SELECT ID FROM B_TABLE)
ORDER BY GRADE, ID